name: Inspect.Org
favicon: null
layout_spectrum: 0.8848908597137779
typography_spectrum: 0.7920263658743352
title: Chit Chat About Inspections
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8bc53d'
    - '#0096e2'
    - '#444444'
    - '#7c7c7c'
  brandStrength: 0.875
  lightness: 0.7747121106367558
  saturation: 0.4105136056896299
  rhythmicContrast: 0.4141205239575356
purpose: []
